// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetFrequency(arg1) {
  return window['go']['main']['App']['SetFrequency'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StartAudio() {
  return window['go']['main']['App']['StartAudio']();
}

export function StopAudio() {
  return window['go']['main']['App']['StopAudio']();
}
