// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetune():Promise<number>;

export function GetMixBalance():Promise<number>;

export function GetMixMode():Promise<number>;

export function GetSync():Promise<boolean>;

export function IsSweeping1():Promise<boolean>;

export function IsSweeping2():Promise<boolean>;

export function SetDetune(arg1:number):Promise<void>;

export function SetFrequency(arg1:number):Promise<void>;

export function SetMixBalance(arg1:number):Promise<void>;

export function SetMixMode(arg1:number):Promise<void>;

export function SetOsc2Frequency(arg1:number):Promise<void>;

export function SetOsc2Volume(arg1:number):Promise<void>;

export function SetOsc2Waveform(arg1:number):Promise<void>;

export function SetSync(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function SetWaveform(arg1:number):Promise<void>;

export function StartAudio():Promise<void>;

export function StartSweep1(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StartSweep2(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StopAudio():Promise<void>;

export function StopSweep1():Promise<void>;

export function StopSweep2():Promise<void>;
