// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetune() {
  return window['go']['main']['App']['GetDetune']();
}

export function GetMixBalance() {
  return window['go']['main']['App']['GetMixBalance']();
}

export function GetMixMode() {
  return window['go']['main']['App']['GetMixMode']();
}

export function GetSync() {
  return window['go']['main']['App']['GetSync']();
}

export function IsSweeping1() {
  return window['go']['main']['App']['IsSweeping1']();
}

export function IsSweeping2() {
  return window['go']['main']['App']['IsSweeping2']();
}

export function SetDetune(arg1) {
  return window['go']['main']['App']['SetDetune'](arg1);
}

export function SetFrequency(arg1) {
  return window['go']['main']['App']['SetFrequency'](arg1);
}

export function SetMixBalance(arg1) {
  return window['go']['main']['App']['SetMixBalance'](arg1);
}

export function SetMixMode(arg1) {
  return window['go']['main']['App']['SetMixMode'](arg1);
}

export function SetOsc2Frequency(arg1) {
  return window['go']['main']['App']['SetOsc2Frequency'](arg1);
}

export function SetOsc2Volume(arg1) {
  return window['go']['main']['App']['SetOsc2Volume'](arg1);
}

export function SetOsc2Waveform(arg1) {
  return window['go']['main']['App']['SetOsc2Waveform'](arg1);
}

export function SetSync(arg1) {
  return window['go']['main']['App']['SetSync'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function SetWaveform(arg1) {
  return window['go']['main']['App']['SetWaveform'](arg1);
}

export function StartAudio() {
  return window['go']['main']['App']['StartAudio']();
}

export function StartSweep1(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSweep1'](arg1, arg2, arg3);
}

export function StartSweep2(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSweep2'](arg1, arg2, arg3);
}

export function StopAudio() {
  return window['go']['main']['App']['StopAudio']();
}

export function StopSweep1() {
  return window['go']['main']['App']['StopSweep1']();
}

export function StopSweep2() {
  return window['go']['main']['App']['StopSweep2']();
}
