// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetFrequency(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StartAudio():Promise<void>;

export function StopAudio():Promise<void>;
